import { MenuGroupType } from '@/types';

export enum MENU_GROUP_NAME_ENUM {
  LOTTO = 'lotto',
  RANDOM_PICKER = 'random-picker',
  QUIZ = 'quiz',
}

export const MENU_LIST: MenuGroupType[] = [
  {
    group: MENU_GROUP_NAME_ENUM.LOTTO,
    label: '로또',
    href: '/' + MENU_GROUP_NAME_ENUM.LOTTO,
    items: [
      {
        href: '/' + MENU_GROUP_NAME_ENUM.LOTTO + '/dashboard',
        label: '로또 대시보드',
        icon: 'LayoutDashboard',
        colorClass: 'text-primary',
        description:
          '저장 번호, 제약 생성, 핫/콜드/지연, 공정성 로그, 예산 트래커를 한 곳에서 관리.',
        example:
          '예: 저장 번호 관리, 통계/지표 확인, 제약 조건으로 조합을 만들 때',
        isConditionalCredit: true,
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.LOTTO + '/normal-generator',
        label: '번호 무작위 생성',
        icon: 'Ticket',
        colorClass: 'text-primary',
        description: 'CSPRNG 기반으로 로또 번호를 무작위 추천.',
        example: '예: 로또 구매 전, 재미로 번호 조합이 필요할 때',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.LOTTO + '/history',
        label: '회차별 당첨 결과',
        icon: 'CalendarSearch',
        colorClass: 'text-primary',
        description: '범위를 지정해 과거 당첨 번호 조회.',
        example: '예: 최근 50회 결과 확인',
        isConditionalCredit: true,
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.LOTTO + '/check',
        label: '번호 채점기',
        icon: 'CheckCircle2',
        colorClass: 'text-primary',
        description: '내 번호와 회차를 비교해 등수 확인.',
        example: '예: 1100회 채점',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.LOTTO + '/analysis',
        label: '통계/패턴 분석',
        icon: 'BarChart2',
        colorClass: 'text-primary',
        description: '빈도, 구간, 홀짝, 합계, 연속수 등 통계 분석.',
        example: '예: 1~200회 빈도 상위/하위 번호',
        isCredit: true,
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.LOTTO + '/advanced-generator',
        label: '고급 번호 생성기',
        icon: 'Wand2',
        colorClass: 'text-primary',
        description: '합계/연속/홀짝/구간/가중치 조건으로 생성.',
        example: '예: 합계 100~200, 연속 최대 2, 최근 제외',
        isCredit: true,
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.LOTTO + '/simulator',
        label: '로또 시뮬레이터',
        icon: 'PlayCircle',
        colorClass: 'text-primary',
        description: '다회 추첨으로 등수 분포 시뮬레이션.',
        example: '예: 5티켓 × 10,000회',
        isCredit: true,
      },
    ],
  },
  {
    group: MENU_GROUP_NAME_ENUM.RANDOM_PICKER,
    label: '랜덤 도구',
    href: '/' + MENU_GROUP_NAME_ENUM.RANDOM_PICKER,
    items: [
      {
        href: '/' + MENU_GROUP_NAME_ENUM.RANDOM_PICKER + '/name-random',
        label: '항목 뽑기',
        icon: 'Wand2',
        colorClass: 'text-primary',
        description: '여러 항목(이름/메뉴/번호) 중 무작위 선택.',
        example: '예: 경품 당첨자 선정, 점심 메뉴 결정 등',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.RANDOM_PICKER + '/seat-assignment',
        label: '자리 배정',
        icon: 'Layout',
        colorClass: 'text-primary',
        description: '참가자와 좌석 수로 랜덤 자리 배정.',
        example: '예: 모임 자리 배치, 시험 좌석 배정 등',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.RANDOM_PICKER + '/team-assignment',
        label: '팀 배정',
        icon: 'Group',
        colorClass: 'text-primary',
        description: '인원과 팀 개수로 랜덤 팀 배정.',
        example: '예: 워크숍 조 편성, 모임 팀 배정 등',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.RANDOM_PICKER + '/ladder-game',
        label: '사다리 타기',
        icon: 'SlidersHorizontal',
        colorClass: 'text-primary',
        description: '참가자/결과 입력 후 랜덤 사다리 결과.',
        example: '예: 점심 메뉴 결정, 벌칙 정하기, 역할 분배 등',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.RANDOM_PICKER + '/dice-game',
        label: '주사위 굴리기',
        icon: 'Dice5',
        colorClass: 'text-primary',
        description: '가상 주사위 결과 확인.',
        example: '예: 순서 정하기, 게임 진행, 벌칙 정하기 등',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.RANDOM_PICKER + '/draw-order',
        label: '랜덤 매칭',
        icon: 'Shuffle',
        colorClass: 'text-primary',
        description: '참가자를 랜덤 순서로 정렬.',
        example: '예: 발표 순서, 게임 순서, 줄 서기 등',
      },
    ],
  },
  {
    group: MENU_GROUP_NAME_ENUM.QUIZ,
    label: 'AI 퀴즈/게임',
    href: '/' + MENU_GROUP_NAME_ENUM.QUIZ,
    items: [
      {
        href: '/' + MENU_GROUP_NAME_ENUM.QUIZ + '/english-word-quiz',
        label: '영어 단어 퀴즈',
        icon: 'SpellCheck',
        colorClass: 'text-primary',
        description: '뜻을 보고 알맞은 영어 단어 맞히기.',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.QUIZ + '/trivia-quiz',
        label: '상식/지식 퀴즈',
        icon: 'Brain',
        colorClass: 'text-primary',
        description: '원하는 주제의 상식/지식 퀴즈.',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.QUIZ + '/four-idiom-quiz',
        label: '사자성어 퀴즈',
        icon: 'ScrollText',
        colorClass: 'text-primary',
        description: '사자성어 정답 맞히기.',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.QUIZ + '/number-match-game',
        label: '숫자 매칭 게임',
        icon: 'SquareStack',
        colorClass: 'text-primary',
        description: '같은 숫자 찾기 게임.',
      },
      {
        href: '/' + MENU_GROUP_NAME_ENUM.QUIZ + '/emoji-translation',
        label: '이모지 번역 퀴즈',
        icon: 'Smile',
        colorClass: 'text-primary',
        description: '이모지 힌트만 보고 정답 맞히기.',
      },
    ],
  },
  // {
  //   group: 'board',
  //   label: '게시판',
  //   items: [
  //     {
  //       href: '/feedback',
  //       label: '건의사항',
  //       description: '건의사항을 확인할 수 있습니다.',
  //     },
  //   ],
  // },
];
